esphome:
  name: garage
  friendly_name: Garage

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Relay control with momentary activation
switch:
  - platform: gpio
    id: relay_switch
    pin: 4
    restore_mode: RESTORE_DEFAULT_OFF

# Reed Switch as a binary sensor
binary_sensor:
  - platform: gpio
    name: "Reed Switch"
    id: garage_reed_switch
    pin:
      number: 14
      mode: INPUT_PULLUP

# Cover configuration for the garage door
cover:
  - platform: template
    name: "Door"
    id: garage_door
    device_class: garage
    open_action:
      - switch.turn_on: relay_switch
      - delay: 0.5s
      - switch.turn_off: relay_switch
    close_action:
      - switch.turn_on: relay_switch
      - delay: 0.5s
      - switch.turn_off: relay_switch
    stop_action:
      - logger.log: "Stop action is not used but must be defined"
    lambda: |-
      if (id(garage_reed_switch).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
